### PR TITLE
Fixes and minor improvements

### PR DESCRIPTION
**Pull request by Klap-in**
wrong date format fix
delete also in non-extension namespaces the plugin data if plugin entry is removed
fix query requesting specific plugins
PHPDocs etc
rewrite of some queries
include bundled plugins again in the listings

### CODE REVIEW

**Comment by selfthinker** [comment]
As a reference, 1fea4e135fe33e8e636d1f8df7eef4d96b5c75cf fixes #94 and splitbrain/dokuwiki#1209.

**Comment by Klap-in** [comment]
Implement title instead of alt.

I moved the exclusion of plugins without download url to the query. Consequence is that everywhere this is applied, but my consideration is that the other checks applied there are of the same kind of checks.

Further the compatibility==(bundled) plugins are now exception at the non-empty downloadurl check. See #95 

Question: 
Sometimes the compatibility==(bundled) is checked, while there is also an list (given in the config) with bundled plugins. Is it better code to use just one method? In that case, only use the list from the config?

**Comment by selfthinker** [comment]
> Sometimes the compatibility==(bundled) is checked, while there is also an list (given in the config) with bundled plugins. Is it better code to use just one method? In that case, only use the list from the config?

Hmm, yes, using only the list is probably best.

Otherwise, code-wise these changes look good to me. :+1:
(But I haven't tested anything because I haven't had the time yet to make the plugin work properly on my local machine.)

**Comment by Klap-in** [comment]
What is the value of the `plugin»pluginrepo»bundled` field in the Config Manager?
does it also contain dokuwiki template?

**Comment by selfthinker** [comment]
> What is the value of the `plugin»pluginrepo»bundled` field in the Config Manager?

It currently is:
```
acl,config,info,extension,popularity,revert,testing,usermanager,template:dokuwiki,authad,authldap,authmysql,authpgsql,authplain,safefnrecode
```

**Comment by Klap-in** [comment]
Added an update again.

**Comment by splitbrain** [comment]
looks good to me, though I haven't tested it

**Comment by Klap-in** [comment]
How to continue on this?
Has someone a test environment available(or who could test that on the live site...)?

**Comment by splitbrain** [comment]
welldoitlive

**Comment by splitbrain** [comment]
This PR's branch is now live. @Klap-in @selfthinker can you check if everything works as expected and give feedback. I'll merge it into master then.

**Comment by splitbrain** [comment]
aaaand it broke...

when enabled no plugins aren't shown on the plugin page anymore. I reverted back to master for now.

**Comment by LarsGit223** [comment]
Is this still an open issue?

I installed klap-in's version locally. Of course my database was empty but I copied the page https://www.dokuwiki.org/plugin:button to my local wiki and it was displayed on my local version of the page https://www.dokuwiki.org/plugins.

So if the problem still exists then it might have to do with the existing database at dokuwiki.org. Is there a way to get it/copy it to my local machine? Or do I need to copy all plugin pages from dokuwiki.org?

**Comment by Klap-in** [comment]
I work very unregularly on this. Often it is simpler to create some manual input. I guess I have some database exports as well, but not sure for this.

**Comment by LarsGit223** [comment]
Ok, if you don't mind I can have a look at this.
But to find the problem I need to find a way to reproduce it locally on my machine.

So if you got some database which is causing the problem seen on the live installation then that would be a good start.

**Comment by Klap-in** [comment]
With only the database you are not complete, the database is related to the real wiki pages. (mainly like the data plugin)
I guess that the getPlugins() function is the most sensitive change here... Further no clue.

**Comment by LarsGit223** [comment]
I added all plugins starting with 'a'. The list of plugins is still displayed. The only problem I could find is that filtering does not work. E.g. if I click on "authentication" in the tag cloud then it is showing nothing instead of showing all authentication plugins.

> when enabled no plugins aren't shown on the plugin page anymore.

Is the problem I described the same problem like you saw (doesn't sound like that).

**Comment by Klap-in** [comment]
This branch should be better now.

@splitbrain could you give it a test run again?

**Comment by Klap-in** [comment]
@splitbrain could you give this branch another try at dokuwiki.org please?

This PR also implements deletion of entries at the namespaces outside the `plugin:` and `template:` namespace. Further my understanding is that the issues from the last try are now fixed.

**Comment by splitbrain** [comment]
I switched to this branch on dokuwiki.org. Seems to work fine on a first look. Let's see for a few days and then merge it.

**Comment by Klap-in** [comment]
My impression is that this stuff works fine, so I suggest merging.

**Comment by splitbrain** [comment]
agreed

**Pull request merged**
