### PR TITLE
Let mark extensions as Not-compatible

### LINKED ISSUE #27: Not compatible plugin
There is no field to tell that a plugin is not compatible with a release, the currents data is "Yes" or "Unknow". I would suggest adding a notcompatible field to allow plugin authors to mark them not compatible.

### PR DESCRIPTION
**Pull request by Klap-in**
Fixes #27

### CODE REVIEW

**Comment by Klap-in** [comment]
Reasonable to merge?

**Comment by splitbrain** [comment]
I guess so. Will this have any effect on the extension manager? If not, should it?

**Comment by Klap-in** [comment]
The `bestcompatible` field in the database is not filled with a not-compatible marked release in case of the `release+` syntax. 

The `bestcompatible

**Comment by Klap-in** [comment]
It adds additional info to the 'compatibility' array
https://github.com/Klap-in/dokuwiki-plugin-pluginrepo/blob/8df829872effed05a98663f8ca478fa94b46055b/helper/repository.php#L390

called with https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/extension/helper/repository.php

for data used in the info blocks:
https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/extension/helper/extension.php#L488
https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/extension/helper/list.php#L410

**Comment by Klap-in** [comment]
So: 
The info block lists only compatible releases, these are now filtered better.
The `compatible` array data retrieved by extension manager is more, but these values aren't used. (Actually that `iscompatible` field is always `1`.)
`bestcompatible` field is used by extension manager for may selection, sofar I understand, so that is a bit more selective by this modification.

**Comment by splitbrain** [comment]
looks good then. can you merge it?

**Comment by selfthinker** [comment]
Meh, I just tried to merge master into this. And although there were 8 conflicts, I think I've done it all correctly. But when I then tried to merge this into master, I had the same conflicts again... :(

So, instead of merging this properly, I have decided to push that merged branch instead, also because someone should check it out again before merging due to that big amount of conflicts. It's the [non-compatible](https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/tree/non-compatible) branch.

**Comment by selfthinker** [comment]
Ah, I saw what I did wrong (I somehow merged the wrong master).
I merged this properly now.

**Pull request merged**
