### PR TITLE
Hide obsoleted extensions or these missing download urls, and explain

### LINKED ISSUE #123: plugins with no type (action, syntax, etc) not visible in API
When you do a search for a plugin where the author set no types, the plugin will not be in the results.

### PR DESCRIPTION
**Pull request by Klap-in**
-  [x] fade entry of obsoleted extension
-  [x] show notice if obsoleted 
-  [x] show notice if missing download url
-  [x] hide obsoleted extension from repo table (i.e. /plugins and /template)
-  [x] remove obsoleted extension from results offered at `api.php`, which is used by Extension Manager. So: remove the extension from search results in the Extension Manager.

- Changed support for the `!obsolete` tag. First the obsolete tag was only respected, if it was the only tag. Now it is also recognized if there are other tags
- first only filtering by type=4 or type=1 was possible, now also the combination i.e. type=5 is possible. Where only results that match type 4 and 1 are shown.
- show warning if plugin entry is saved outside the `plugin` or `template` namespace. 
- in the `---- pluginrepo ----` the option `tablelayout: old`, to shown the old table style, is removed
- removed the filtering in the `/lib/plugins/pluginrepo/repository.php` API endpoint.
- add CLI type
- show also plugins without any types, but only CSS/JS by assigning artificial a type. Fixes #123
- improve stored tags by removing prefix by `:`, #113. Fixes also linking in Extension Manager

### CODE REVIEW

**Comment by Klap-in** [comment]
Impression of the entry:
entry_obsoleted

**Comment by LarsGit223** [comment]
:thumbsup: Looks good. I like the fading effect. The user immediately sees that something is different.

**Comment by Klap-in** [comment]
The old repository API `/lib/plugins/pluginrepo/repository.php` returns plugin/template data as XML.
I know that the Translation Tool uses this API for its information.

Are there other usages of this old API end point?

If the old end point is not used anymore, I will simplify it, so it only useful for the Translation Tool. Later I will replace it by the `api.php`.

(The newer end point is `lib/plugins/pluginrepo/api.php`. This end point is used by e.g. the Extension Manager.)

**Comment by Klap-in** [comment]
I think it is fine for merge. I tried to test all the new bits. Any comments?

**Comment by Klap-in** [comment]
@splitbrain do you have time to publish this on dokuwiki.org?

**Comment by splitbrain** [comment]
merged and online. can be seen at https://www.dokuwiki.org/plugin:spellcheck

**Pull request merged**
